[package]
name = "oskr"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
bincode = "1.3.3"
core_affinity = "0.5.10"
derivative = "2.2.0"
futures = "0.3.19"
rand = "0.8.4"
serde = "1.0.135"
serde_derive = "1.0.135"
smallvec = "1.8.0"
tokio = { version = "1.15.0", features = ["full", "test-util"] }

[build-dependencies]
cc = "1.0.72"
pkg-config = "0.3.24"

[features]
